project:
  name: cfn-s3buckets
  regions:
  - us-east-1
tests:
  public:
    template: ./private.json
    parameters:
      BucketName: cfn-s3buckets-alpha-bravo-charlie-delta
  private:
    template: ./public.json
    parameters:
      BucketName: cfn-s3buckets-edward-francis-gerald